#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on precise-essex."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='precise')
    deployment.run_tests()
