#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on precise-icehouse."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='precise',
                                        openstack='cloud:precise-icehouse',
                                        source='cloud:precise-updates/icehouse')
    deployment.run_tests()
