#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on trusty-juno."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-juno',
                                        source='cloud:trusty-updates/juno')
    deployment.run_tests()
