#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on trusty-kilo."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-kilo',
                                        source='cloud:trusty-updates/kilo')
    deployment.run_tests()
