#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on trusty-liberty."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-liberty',
                                        source='cloud:trusty-updates/liberty')
    deployment.run_tests()
