#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on trusty-mitaka."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-mitaka',
                                        source='cloud:trusty-updates/mitaka')
    deployment.run_tests()
