#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on vivid-kilo."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='vivid')
    deployment.run_tests()
