#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on wily-liberty."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='wily')
    deployment.run_tests()
