#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on xenial-mitaka."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='xenial')
    deployment.run_tests()
