#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on precise-folsom."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='precise',
                                          openstack='cloud:precise-folsom',
                                          source='cloud:precise-updates/folsom')
    deployment.run_tests()
