#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on precise-grizzly."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='precise',
                                         openstack='cloud:precise-grizzly',
                                         source='cloud:precise-updates/grizzly')
    deployment.run_tests()
