#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on precise-havana."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='precise',
                                          openstack='cloud:precise-havana',
                                          source='cloud:precise-updates/havana')
    deployment.run_tests()
