#!/usr/bin/python

"""Amulet tests on a basic swift-storage deployment on trusty-icehouse."""

from basic_deployment import SwiftStorageBasicDeployment

if __name__ == '__main__':
    deployment = SwiftStorageBasicDeployment(series='trusty')
    deployment.run_tests()
